export default {
  name: 'Cubes',
  modules: [
    'Move',
    'Rotate',
    'Create',
    'Copy',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'BackgroundColor',
    'BorderColor',
    'Translate',
    'Zoom',
    'Grid',
  ],
  kit: 'cubesKit',
  extension: 'agc',
  themeColor: '#f46c2e',
};
