export default {
  name: 'Cubes',
  modules: [
    'Create',
    'Move',
    'Rotate',
    'Copy',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'Color',
    // 'BackgroundColor',
    // 'BorderColor',
    'Translate',
    'Zoom',
    'Grid',
  ],
  kit: 'cubesKit',
  extension: 'agc',
  themeColor: '#f46c2e',
  themeColorSoft: '#FED3C2',
};
