export default {
  name: 'Geometrie',
  modules: [
    'Move',
    'Rotate',
    'CreateGeometry',
    'Reverse',
    'BuildCenter',
    'Divide',
    'Cut',
    'Copy',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'BackgroundColor',
    'BorderColor',
    'Translate',
    'Zoom',
    'Grid',
    'Transform',
  ],
  extension: 'agl',
  themeColor: '#FF0000',
};
