export default {
  "name": "Grandeurs",
  "modules": [
    "Move",
    "Rotate",
    "Create",
    "Reverse",
    "BuildCenter",
    "Divide",
    "Cut",
    "Copy",
    "Merge",
    "Delete",
    "Group",
    "Ungroup",
    "ToBackground",
    "BackgroundColor",
    "BorderColor",
    "Opacity",
    "Biface",
    "Translate",
    "Zoom",
    "Grid"],
  "kit": "grandeursKit",
  "extension": "agg"
}