export default {
  name: 'Grandeurs',
  modules: [
    'Move',
    'Rotate',
    'Create',
    'Reverse',
    'BuildCenter',
    'Divide',
    'Cut',
    'Copy',
    'Merge',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'Color',
    // 'BackgroundColor',
    // 'BorderColor',
    'Opacity',
    'Biface',
    'Translate',
    'Zoom',
    'Grid',
  ],
  kit: 'grandeursKit',
  extension: 'agg',
  themeColor: '#57D99B',
  themeColorSoft: '#C4F1D9',
};
