export default {
  name: 'Cubes',
  modules: [
    'Create',
    'Move',
    'Rotate',
    'Copy',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'Color',
    'Translate',
    'Zoom',
    'Grid',
  ],
  kit: 'cubesKit',
  extensions: ['.agc'],
  themeColor: '#f46c2e',
  themeColorSoft: '#FED3C2',
};
