export default {
  name: 'Geometrie',
  modules: [
    'CreatePoint',
    'CreateLine',
    'CreateTriangle',
    'CreateQuadrilateral',
    'CreateRegular',
    'CreateIrregular',
    'CreateCircle',
    'Move',
    'Rotate',
    'Reverse',
    'OrthogonalSymetry',
    'CentralSymetry',
    'Translation',
    'Rotation',
    'Transform',
    'Divide',
    'Cut',
    'BuildCenter',
    'Copy',
    'Duplicate',
    'ScalarMultiplication',
    'Delete',
    'Group',
    'Ungroup',
    'ToBackground',
    'Color',
    'Opacity',
    'Hide',
    'Show',
    'Biface',
    'Translate',
    'Zoom',
    'Grid',
  ],
  extensions: ['.agl'],
  kit: false,
  themeColor: '#888888',
  themeColorSoft: '#B8B8B8',
  textColor: '#FFF'
};
